scheduler_lag: 1000         # milliseconds
status_lag: 5000            # milliseconds

register_retries: 10        # number of registration retries
register_retry_wait: 5      # seconds

daemon_port: 5001           # port number

num_cpus_per_child: 2       # integer
memory_per_child: 512       # integer

num_cpus_per_head: 2        # integer
memory_per_head: 512        # integer

request_timeout: 100        # milliseconds

default_n_nodes: 1
default_n_procs: 1
default_n_cpus_per_node: 1
default_mem_per_node: 100
default_time_limit: 0
