version: "3.9"

services:
  computenode:
    build: ./computenode
    command: /cm/bin/cmdaemon
    networks:
      - cm
    volumes:
      - ./drive/home:/home
      - ./cm:/cm
    depends_on:
      - headnode
    environment:
      CM_PATH: /cm/
      CM_SERVER_TYPE: node
      CM_MASTER_ADDR: headnode
  headnode:
    build: ./headnode
    command: /cm/bin/cmdaemon
    networks:
      - cm
    volumes:
      - ./drive/home:/home
      - ./cm:/cm
    environment:
      CM_PATH: /cm/
      CM_SERVER_TYPE: head
      CM_DATABASE_ADDR: database
      CM_DATABASE_PORT: 27017
      CM_DATABASE_NAME: cmdb
    depends_on:
      - database

  database:
    image: mongo:5.0.5
    networks:
      - cm
    volumes:
      - ./drive/db:/data/db

networks:
  cm:
    name: cluster_manager
