version: "3.9"

services:
  computenode:
    build: ./computenode
    command: /cm/bin/cmdaemon
    networks:
      - cm
    volumes:
      - ./drive/home:/home
      - ./cm:/cm
    depends_on:
      - headnode
    environment:
      CM_SERVER_TYPE: node
      CM_MASTER_ADDR: headnode
  headnode:
    build: ./headnode
    command: /cm/bin/cmdaemon
    networks:
      - cm
    volumes:
      - ./drive/home:/home
      - ./cm:/cm
    environment:
      CM_SERVER_TYPE: head
    depends_on:
      - database

  database:
    image: mongodb:5.0.5
    networks:
      - cm

networks:
  cm:
    name: cluster_manager
