#!/usr/bin/env python3

import logging
import os

from src.socket import Socket

logging.basicConfig(format='%(levelname)s:%(message)s', level=logging.INFO)
_logger = logging.getLogger(__name__)


if __name__ == "__main__":
    if "HEADNODE" in os.environ:
        sock = Socket('')
        sock.bind(7842)
        sock.connect(os.environ["HEADNODE"], 5000)
        _logger.info(f"Transmitting message")
        sock.send("Hey there")
        msg = sock.receive()
        _logger.info(f"Server responded with: {msg}")
        sock.close()
    else:
        _logger.warn("HEADNODE not found in env vars, quitting.")
